- hosts: localhost
  remote_user: ubuntu
  become: true
  vars:
    ansible_ssh_private_key_file: "/home/ubuntu/id_rsa"
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    admin_configuration: "/var/lib/jenkins/init.groovy.d"
  tasks:
    - name: Make runSetupWizard false
      command: sed -i 's/JAVA_ARGS="-Djava.awt.headless=true"/JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"/g' /etc/default/jenkins

    - name: Create a groovy file to disable basic security
      copy: src={{ item }} dest={{ admin_configuration }}/
      with_items:
        - basic-security.groovy
        - configure-jenkins-admin.groovy
        
    - name: restart Jenkins
      service: 
        name: jenkins
        state: restarted
        
    - name: Remove groovy file
      file:
        path:
          - "{{ admin_configuration }}/basic-security.groovy"
          - "{{ admin_configuration }}/configure-jenkins-admin.groovy"
        state: absent
